//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apotek.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class jeni
    {
        public jeni()
        {
            this.obats = new HashSet<obat>();
        }
    
        public string id_jenis { get; set; }
        public string nama_jenis { get; set; }
    
        public virtual ICollection<obat> obats { get; set; }
    }
}
