//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apotek.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelanggan
    {
        public pelanggan()
        {
            this.faktur_penjualan = new HashSet<faktur_penjualan>();
        }
    
        public string id_pelanggan { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string jenis_kelamin { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<faktur_penjualan> faktur_penjualan { get; set; }
    }
}
