//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apotek.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.faktur_supply = new HashSet<faktur_supply>();
            this.obats = new HashSet<obat>();
        }
    
        public string id_supplier { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string telp { get; set; }
    
        public virtual ICollection<faktur_supply> faktur_supply { get; set; }
        public virtual ICollection<obat> obats { get; set; }
    }
}
